#!/usr/bin/env sh

export PATH="${HOME}/local/bin:${PATH}"
. ~/local/alias
. ~/local/func

export EDITOR=nano
cp ~/local/tmux.conf ~/.tmux.conf
rm ~/local/tmux.conf
export TZ='Africa/Lagos'
unset TMUX

export PS1="\[\e[0m\]\[\e[38;5;35m\]╭─(\[\e[38;5;38m\]\t\[\e[38;5;35m\])-(\[\e[38;5;38m\]\j\[\e[38;5;35m\])-(\[\e[38;5;38m\]\H\[\e[38;5;35m\])-(\[\e[38;5;38m\]\w\[\e[38;5;35m\])\n\[\e[38;5;35m\]╰─% \[\e[0m\]"
clear

tmux_activate
